// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"
)

type Querier interface {
	GetAllBoats(ctx context.Context, arg GetAllBoatsParams) ([]Boat, error)
	// -- name: CreateBoat :one
	// INSERT INTO Boats (
	//   owner,
	//   balance,
	//   currency
	// ) VALUES (
	//   $1, $2, $3
	// ) RETURNING *;
	GetBoat(ctx context.Context, id int32) (Boat, error)
}

var _ Querier = (*Queries)(nil)
