// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"
)

type Querier interface {
	CreateBoat(ctx context.Context, arg CreateBoatParams) (Boat, error)
	DeleteBoat(ctx context.Context, id int32) error
	GetAllBoats(ctx context.Context, arg GetAllBoatsParams) ([]Boat, error)
	GetBoat(ctx context.Context, id int32) (Boat, error)
	UpdateBoat(ctx context.Context, arg UpdateBoatParams) (Boat, error)
}

var _ Querier = (*Queries)(nil)
